// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOKZXtCZYNBif55y88Hs313WbvgFL3Fv4',
    appId: '1:188444860939:web:5969d9a976d5d7e2a6dd0e',
    messagingSenderId: '188444860939',
    projectId: 'andand-db',
    authDomain: 'andand-db.firebaseapp.com',
    storageBucket: 'andand-db.appspot.com',
    measurementId: 'G-P8DT1J74LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzBLiIivuDM4OYJ5nGuMJgEx8iAOOWxw',
    appId: '1:188444860939:android:cdfb412e9da28883a6dd0e',
    messagingSenderId: '188444860939',
    projectId: 'andand-db',
    storageBucket: 'andand-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDysMx_TaDTBxAHeTrhhQ7A-6jQQ0Jw_mQ',
    appId: '1:188444860939:ios:b916742e32f168e9a6dd0e',
    messagingSenderId: '188444860939',
    projectId: 'andand-db',
    storageBucket: 'andand-db.appspot.com',
    iosBundleId: 'com.example.andand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDysMx_TaDTBxAHeTrhhQ7A-6jQQ0Jw_mQ',
    appId: '1:188444860939:ios:9041eebaff9f1023a6dd0e',
    messagingSenderId: '188444860939',
    projectId: 'andand-db',
    storageBucket: 'andand-db.appspot.com',
    iosBundleId: 'com.example.andand.RunnerTests',
  );
}
