// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaaP9xCD2PzQBBpKysAAbCLQz5zpsUxjs',
    appId: '1:22819091903:web:42f2d16323dd02692f1d0a',
    messagingSenderId: '22819091903',
    projectId: 'dbbase-andand',
    authDomain: 'dbbase-andand.firebaseapp.com',
    storageBucket: 'dbbase-andand.appspot.com',
    measurementId: 'G-JF1MW53LT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGnk3_ioSaYP2fHcs97nYwEiGGJWfPpro',
    appId: '1:22819091903:android:0494ab78cffd62db2f1d0a',
    messagingSenderId: '22819091903',
    projectId: 'dbbase-andand',
    storageBucket: 'dbbase-andand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmF6rbv6i2Sikh3hHfYnXpKwUJ0MDR4XM',
    appId: '1:22819091903:ios:e97a07c2a1ed5acb2f1d0a',
    messagingSenderId: '22819091903',
    projectId: 'dbbase-andand',
    storageBucket: 'dbbase-andand.appspot.com',
    androidClientId: '22819091903-7emb9mku038dfnf25jhuogfgdlfnrps6.apps.googleusercontent.com',
    iosClientId: '22819091903-pn1nvjak1ba9etfm4jtubv8us453n4v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.andand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmF6rbv6i2Sikh3hHfYnXpKwUJ0MDR4XM',
    appId: '1:22819091903:ios:c87578f54d81b58f2f1d0a',
    messagingSenderId: '22819091903',
    projectId: 'dbbase-andand',
    storageBucket: 'dbbase-andand.appspot.com',
    androidClientId: '22819091903-7emb9mku038dfnf25jhuogfgdlfnrps6.apps.googleusercontent.com',
    iosClientId: '22819091903-psqgpojbvu77ig7ofoknn4utc8vvgv3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.andand.RunnerTests',
  );
}
